name: Coverity

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * 2,4,6'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t coverity-img .
      - name: Run Coverity
        run: |
          set -e
          docker run --name cov-worker --env COVERITY_SCAN_NOTIFICATION_EMAIL --env COVERITY_SCAN_TOKEN --env COVERITY_DRY_RUN coverity-img
          docker cp cov-worker:/root/ffmpeg/cov-int.tgz cov-int.tgz
        env:
          COVERITY_SCAN_NOTIFICATION_EMAIL: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_DRY_RUN: ${{ github.event_name != 'schedule' }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: cov-int
          path: cov-int.tgz
