name: Coverity

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16 * * 2,4,6'

jobs:
  coverity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: coverity-img:latest
          load: true
          pull: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
      - name: Run Coverity
        run: |
          set -e
          docker run --name cov-worker --env COVERITY_SCAN_NOTIFICATION_EMAIL --env COVERITY_SCAN_TOKEN --env COVERITY_DRY_RUN coverity-img
          docker cp cov-worker:/root/cov-int.tgz cov-int.tgz
        env:
          COVERITY_SCAN_NOTIFICATION_EMAIL: ${{ secrets.COVERITY_SCAN_NOTIFICATION_EMAIL }}
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_DRY_RUN: ${{ github.event_name != 'schedule' }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cov-int
          path: cov-int.tgz
  keepalive:
    name: Keepalive Workflow
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
